import io
import json
import os
import streamlit as st

from agents.documentation_agent import DocumentationAgent
from ui.components import dataset_banner, require_dataset, glass_metric
from utils.session_manager import get_dataframe, get_dataset_name, SessionKeys
from utils.styles import render_hero


def _create_notebook_payload(dataset_name: str, rows: int, cols: int):
    notebook = {
        "cells": [
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    f"# AutoDS Notebook for {dataset_name}\n",
                    "This notebook contains an overview of dataset analysis and model preparation from AutoDS Agent.\n",
                ],
            },
            {
                "cell_type": "code",
                "metadata": {},
                "source": [
                    "import pandas as pd\n",
                    "# Load and explore your dataset here\n",
                ],
            },
        ],
        "metadata": {"kernelspec": {"name": "python3", "language": "python", "display_name": "Python 3"}},
        "nbformat": 4,
        "nbformat_minor": 5,
    }
    return notebook


def render():
    render_hero("Documentation Hub", "Download reports, notebooks, and project artifacts")

    if not require_dataset():
        return

    df = get_dataframe()
    dataset_banner()
    doc_agent = DocumentationAgent()

    model_name = st.session_state.get(SessionKeys.BEST_MODEL_NAME) or "Unnamed Model"
    problem_type = st.session_state.get(SessionKeys.PROBLEM_TYPE) or "Unknown"
    results = st.session_state.get(SessionKeys.RESULTS) or {}
    best_score = results.get(model_name, None)

    st.markdown("---")
    st.subheader("Available Downloads")

    dataset_card = doc_agent.generate_dataset_card({
        "dataset_name": get_dataset_name(),
        "source": "Uploaded dataset",
        "samples": df.shape[0],
        "features": list(df.columns),
        "target_variable": st.session_state.get(SessionKeys.TARGET_COLUMN),
        "domain": problem_type,
        "quality_score": int(df.isnull().mean().mean() * 100),
        "risks": [],
    })
    model_card = doc_agent.generate_model_card(
        {
            "model_name": model_name,
            "framework": "AutoDS Model",
            "version": "v1",
            "description": "Model generated by AutoDS pipeline.",
            "training_configuration": {"problem_type": problem_type},
        },
        {"best_score": best_score},
    )
    experiment_report = {
        "best_model": model_name,
        "metrics": results,
        "notes": ["Generated through the AutoDS pipeline."],
    }

    pdf_path = st.session_state.get(SessionKeys.REPORT_PATH)
    if pdf_path and os.path.exists(pdf_path):
        with open(pdf_path, "rb") as handle:
            btn = st.download_button(
                "Download Executive PDF report",
                handle,
                file_name="AutoDS_Executive_Report.pdf",
                mime="application/pdf",
            )
    else:
        st.info("Generate the AI report in the Report Center to download the executive PDF.")

    st.download_button(
        "Download Dataset Card (JSON)",
        json.dumps(dataset_card, indent=2),
        file_name="dataset_card.json",
        mime="application/json",
    )
    st.download_button(
        "Download Model Card (JSON)",
        json.dumps(model_card, indent=2),
        file_name="model_card.json",
        mime="application/json",
    )
    st.download_button(
        "Download Experiment Report (JSON)",
        json.dumps(experiment_report, indent=2),
        file_name="experiment_report.json",
        mime="application/json",
    )

    notebook_payload = _create_notebook_payload(get_dataset_name(), df.shape[0], df.shape[1])
    st.download_button(
        "Download Jupyter Notebook",
        json.dumps(notebook_payload, indent=2),
        file_name="auto_ds_notebook.ipynb",
        mime="application/json",
    )

    try:
        with open("agents/master_autonomous_pipeline.py", "r", encoding="utf-8") as source:
            source_code = source.read()
        st.download_button(
            "Download Python Source Code",
            source_code,
            file_name="master_autonomous_pipeline.py",
            mime="text/plain",
        )
    except FileNotFoundError:
        st.warning("Python source file could not be loaded for download.")

    st.markdown("---")
    st.subheader("Documentation Summary")
    st.write("Use the files above to support executive reporting, product documentation, and technical handoff.")
    glass_metric("", "Dataset Card", "Ready")
    glass_metric("🏷️", "Model Card", "Ready")
    glass_metric("", "Experiment Report", "Ready")
    glass_metric("📓", "Notebook", "Ready")
    glass_metric("🧾", "Source Code", "Ready")

    st.markdown("---")
    st.subheader("Knowledge Base & Reports")
    try:
        entries = doc_agent.list_entries(limit=100)
    except Exception:
        entries = []

    if not entries:
        st.info("No documentation entries found in the knowledge base.")
    else:
        for idx, entry in enumerate(entries, start=1):
            with st.expander(f"{entry.get('timestamp', '')} — {entry.get('title', 'Untitled')}"):
                st.write(entry.get('content', ''))
                st.write("Tags:", ", ".join(entry.get('tags', [])))
                st.download_button(
                    f"Download JSON (entry {idx})",
                    doc_agent.export_json(entry),
                    file_name=f"doc_entry_{idx}.json",
                    mime="application/json",
                )
                st.download_button(
                    f"Download Markdown (entry {idx})",
                    doc_agent.export_markdown(entry),
                    file_name=f"doc_entry_{idx}.md",
                    mime="text/markdown",
                )
                st.download_button(
                    f"Download Text (entry {idx})",
                    doc_agent.export_text(entry),
                    file_name=f"doc_entry_{idx}.txt",
                    mime="text/plain",
                )
